import { GOOGLE_DRIVE_FILE_TREE_LOADING_SUPPORT_TEXT } from '../interfaces/main';

export const GOOGLE_DRIVE_FILE_TREE_LOADING_SUPPORT_TEXT_CONTENT: Record<GOOGLE_DRIVE_FILE_TREE_LOADING_SUPPORT_TEXT, string> = {
  [GOOGLE_DRIVE_FILE_TREE_LOADING_SUPPORT_TEXT.SETUP]: 'Setting up Google Drive',
  [GOOGLE_DRIVE_FILE_TREE_LOADING_SUPPORT_TEXT.FETCHING]: 'Fetching files and folders',
} as const;
